name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports: ['6379:6379']
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: { node-version: 18 }

      - name: Install & Test Backend
        working-directory: packages/backend
        run: |
          npm install
          npm run build
          npm test

      - name: Install & Test Frontend
        working-directory: packages/frontend
        run: |
          npm install
          npm run build
          npm test